server:
  port: 8888
  tomcat:
    uri-encoding: utf-8
  servlet:
    encoding:
      force: true
      charset: utf-8
      enabled: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studydb?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #      logic-delete-field: delFlag
      #      logic-delete-value: 1
      #      logic-not-delete-value: 0
      id-type: auto

